import { invoke } from '@tauri-apps/api/core';
import { useCallback, useEffect, useMemo, useRef, useState } from 'react';
import { createRoot } from 'react-dom/client';
import ReactMarkdown from 'react-markdown';
import { createApi } from './api';
import type { Issue, Job, Repository, Settings } from './types';
import './style.css';

const id = () => crypto.randomUUID();
const api = createApi((path, init = {}) => invoke('worker_request', { method: init.method ?? 'GET', path, body: init.body ? JSON.parse(init.body as string) : null, idempotencyKey: (init.headers as Record<string,string> | undefined)?.['Idempotency-Key'] }));
type Tab = 'settings'|'repositories'|'issues'|'jobs'|'recovery';
function App() {
 const [tab,setTab]=useState<Tab>('settings'), [settings,setSettings]=useState<Settings|null>(null), [repos,setRepos]=useState<Repository[]>([]), [issues,setIssues]=useState<Issue[]>([]), [jobs,setJobs]=useState<Job[]>([]), [selected,setSelected]=useState<Issue|null>(null), [message,setMessage]=useState('Configure the Worker connection to begin.'), [offline,setOffline]=useState(false), [filter,setFilter]=useState<number|undefined>(), [recovery,setRecovery]=useState<any[]>([]); const busy=useRef(false); const delay=useRef(10_000);
 const load=useCallback(async()=>{if(busy.current)return;busy.current=true;try { const [r,i,j]=await Promise.all([api.repositories(),api.issues(filter),api.jobs()]);setRepos(r.items);setIssues(i.items);setJobs(j.items);setOffline(false);delay.current=10_000;} catch(e:any){setOffline(true);setMessage(e.message||'Unable to reach Worker');delay.current=Math.min(delay.current*2,60_000)}finally{busy.current=false}},[filter]);
 useEffect(()=>{invoke<Settings>('get_settings').then(setSettings).catch(e=>setMessage(String(e)));invoke<any[]>('list_checkpoints').then(setRecovery);},[]);
 useEffect(()=>{if(!settings?.hasToken)return;let cancelled=false;const tick=async()=>{await load();if(!cancelled)setTimeout(tick,delay.current)};tick();return()=>{cancelled=true}},[settings?.hasToken,load]);
 const approve=async(issue:Issue)=>{try{setMessage('Approving issue…');await api.approve(issue.id,issue.version,id());setMessage('Issue approved and queued.');await load()}catch(e:any){setMessage(e.message)}};
 const run=async(job:Job)=>{try{setMessage('Claiming and starting local runner…');const issue=issues.find(i=>i.id===job.issue_id);const enriched={...job,repository_id:issue?.repository_id,issue_number:issue?.number};await invoke('execute_job',{job:enriched});setMessage('Job completed.');await load();setRecovery(await invoke('list_checkpoints'))}catch(e:any){setMessage(`Job stopped: ${e}`)}};
 const content=useMemo(()=> {
  if(tab==='settings') return <SettingsPane settings={settings} onSaved={async()=>setSettings(await invoke('get_settings'))} message={message}/>;
  if(tab==='repositories') return <><section className="actions"><button onClick={async()=>{await api.syncGithub();setMessage('Repository discovery requested.');await load()}}>Discover GitHub repositories</button><button onClick={load}>Refresh</button></section><div className="cards">{repos.map(r=><article className="card" key={r.id}><h3>{r.full_name}</h3><small>{r.access_status==='active'?'Accessible':'Access revoked'}</small><label><input type="checkbox" checked={Boolean(r.active)} disabled={r.access_status!=='active'} onChange={async e=>{await api.setRepository(r.id,e.target.checked);await load()}}/> Follow issues</label><RepoLink repo={r} onSaved={()=>setMessage('Local checkout saved.')}/><button onClick={()=>api.syncRepository(r.id).then(()=>setMessage('Sync requested'))}>Sync issues</button></article>)}</div></>;
  if(tab==='issues') return <><div className="actions"><select value={filter??''} onChange={e=>setFilter(e.target.value?Number(e.target.value):undefined)}><option value="">All repositories</option>{repos.map(r=><option value={r.id} key={r.id}>{r.full_name}</option>)}</select><button onClick={load}>Refresh</button></div><div className="split"><div className="list">{issues.map(i=><button className={selected?.id===i.id?'selected':''} onClick={()=>setSelected(i)} key={i.id}><b>#{i.number} {i.title}</b><small>{i.full_name} · {i.github_updated_at}</small></button>) || <p>No issues.</p>}</div><article className="detail">{selected ? <><h2>#{selected.number} {selected.title}</h2><p>{labels(selected.labels_json).map(x=><span className="label" key={x}>{x}</span>)}</p><ReactMarkdown skipHtml>{selected.body||'_No description._'}</ReactMarkdown><button onClick={()=>approve(selected)} disabled={!Boolean(selected.active)||selected.state!=='open'}>Approve for local execution</button></>:<p>Select an issue to review its immutable version before approval.</p>}</article></div></>;
  if(tab==='jobs') return <><p className="hint">The app executes at most one job. It will not run a job without a trusted checkout link.</p><div className="cards">{jobs.map(j=><article className="card" key={j.id}><h3>{j.issue_title}</h3><p><b>{j.status}</b> {j.phase&&`· ${j.phase}`}</p>{j.result_summary&&<p>{j.result_summary}</p>}{j.pr_url&&<a href={j.pr_url}>Open draft PR</a>}{j.status==='queued'&&<button onClick={()=>run(j)}>Run locally</button>}{['interrupted','failed','cancelled'].includes(j.status)&&<button onClick={()=>api.retry(j.id).then(load)}>Create retry after inspection</button>}</article>)}</div></>;
  return <><p className="hint">Interrupted jobs are never resumed automatically. Inspect the retained worktree, branch, SHA and server state before explicitly retrying.</p><div className="cards">{recovery.map(c=><article className="card" key={c.job_id}><h3>{c.job_id}</h3><p>{c.phase} · {c.updated_at}</p><code>{c.worktree}</code>{c.commit_sha&&<p>Commit: {c.commit_sha}</p>}{c.pr_url&&<a href={c.pr_url}>Open PR</a>}</article>)}{!recovery.length&&<p>No local checkpoints yet.</p>}</div></>;
 },[tab,settings,message,repos,issues,selected,jobs,recovery,filter,load]);
 return <main><aside><h1>Issue Pilot</h1>{(['settings','repositories','issues','jobs','recovery'] as Tab[]).map(t=><button key={t} className={tab===t?'nav active':'nav'} onClick={()=>setTab(t)}>{t}</button>)}<footer className={offline?'offline':''}>{offline?'Offline · retrying':'Connected / ready'}</footer></aside><section className="workspace"><header>{message}</header>{content}</section></main>
}
function labels(raw:string): string[]{try{const parsed: unknown=JSON.parse(raw);return Array.isArray(parsed)?parsed.filter((x): x is string=>typeof x==='string'):[]}catch{return []}}
function SettingsPane({settings,onSaved,message}:{settings:Settings|null,onSaved:()=>Promise<void>,message:string}){const [url,setUrl]=useState(''),[token,setToken]=useState(''),[codex,setCodex]=useState('codex'),[git,setGit]=useState('git'),[gh,setGh]=useState('gh'),[tools,setTools]=useState<any>();useEffect(()=>{if(settings){setUrl(settings.workerUrl);setCodex(settings.codexPath);setGit(settings.gitPath);setGh(settings.ghPath)}},[settings]);return <section className="form"><h2>Connection and local tools</h2><p>The Worker token is held by the OS credential store, never browser storage.</p><label>Worker URL<input value={url} onChange={e=>setUrl(e.target.value)} placeholder="https://issue-pilot.example.workers.dev"/></label><label>Desktop token<input type="password" value={token} onChange={e=>setToken(e.target.value)} placeholder={settings?.hasToken?'Stored securely (enter only to replace)':'Paste token'}/></label><div className="grid"><label>Codex path<input value={codex} onChange={e=>setCodex(e.target.value)}/></label><label>Git path<input value={git} onChange={e=>setGit(e.target.value)}/></label><label>gh path<input value={gh} onChange={e=>setGh(e.target.value)}/></label></div><button onClick={async()=>{await invoke('save_settings',{input:{workerUrl:url,token:token||null,codexPath:codex,gitPath:git,ghPath:gh}});setToken('');await onSaved()}}>Save securely</button><button onClick={async()=>setTools(await invoke('check_tools'))}>Check CLI access</button>{tools&&<pre>{JSON.stringify(tools,null,2)}</pre>}<p className="hint">{message}</p></section>}
function RepoLink({repo,onSaved}:{repo:Repository,onSaved:()=>void}){const [path,setPath]=useState(''),[base,setBase]=useState('main'),[tests,setTests]=useState('npm test');return <details><summary>Link local checkout</summary><label>Path<input value={path} onChange={e=>setPath(e.target.value)} placeholder="/Users/me/code/repo"/></label><label>Base branch<input value={base} onChange={e=>setBase(e.target.value)}/></label><label>Confirmed test command<input value={tests} onChange={e=>setTests(e.target.value)}/></label><button onClick={async()=>{await invoke('save_repo_link',{input:{repositoryId:repo.id,localPath:path,baseBranch:base,testCommand:tests}});onSaved()}}>Save link</button></details>}
export default App;

const root = document.getElementById('root');
if (!root) throw new Error('Issue Pilot root element is missing');
createRoot(root).render(<App />);
